name: map_project2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  lottie: ^3.2.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  